spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Fegin开启熔断器
feign:
  hystrix:
    enabled: true
